llm:
  use: siliconflow
  siliconflow:
    - api_key: "sk-hrvpfobqslzrgfxunjrjdflttskthedqtsbifmzfqozrtfza"
      api_base: "https://api.siliconflow.cn/v1/chat/completions"
      model: "Qwen/Qwen3-14B"
      rate_limit: 20

    - api_key: "sk-varotcommbpttwkmvrcznqgroqewaglrtcnlskyvaabgolim"
      api_base: "https://api.siliconflow.cn/v1/chat/completions"
      model: "Qwen/Qwen3-14B"
      rate_limit: 20

    - api_key: "sk-klnyioflaucgizixndytgxrlwhyrconbzajbgtkovsagttha"
      api_base: "https://api.siliconflow.cn/v1/chat/completions"
      model: "Qwen/Qwen3-14B"
      rate_limit: 20

    - api_key: "sk-enzbbnvtcnyfsbuawhjgjsiuwdqmxhpinufobjhvtllmhxuy"
      api_base: "https://api.siliconflow.cn/v1/chat/completions"
      model: "Qwen/Qwen3-14B"
      rate_limit: 20

    - api_key: "sk-dcimxgrikpskounlgqjikcjyliiseywxtiwpkcexqhorfhjd"
      api_base: "https://api.siliconflow.cn/v1/chat/completions"
      model: "Qwen/Qwen3-14B"
      rate_limit: 20

    - api_key: "sk-crhbholxcqldbqimnluhpikfuomfjdcrwydybxczxwvteoxx"
      api_base: "https://api.siliconflow.cn/v1/chat/completions"
      model: "Qwen/Qwen3-14B"
      rate_limit: 20

    - api_key: "sk-lylknofeldklwowhtsmjnogzvvhzyktrjjrhfswnznrxruja"
      api_base: "https://api.siliconflow.cn/v1/chat/completions"
      model: "Qwen/Qwen3-14B"
      rate_limit: 20

    - api_key: "sk-zeruudoskwllezurejdaqtoautnomiqtphpyofacbnbzmybe"
      api_base: "https://api.siliconflow.cn/v1/chat/completions"
      model: "Qwen/Qwen3-14B"
      rate_limit: 20

    - api_key: "sk-vhfwhragmjtribovcmvkvfyyrqvargpqdeqwqcfllateeqtz"
      api_base: "https://api.siliconflow.cn/v1/chat/completions"
      model: "Qwen/Qwen3-14B"
      rate_limit: 20

    - api_key: "sk-xlyeovdljcpoqjhxaswobnagblkaxyomezmxczddkjdtilew"
      api_base: "https://api.siliconflow.cn/v1/chat/completions"
      model: "Qwen/Qwen3-14B"
      rate_limit: 20
