llm:
  use: siliconflow
  siliconflow:
    - api_key: "sk-xxx"
      api_base: "https://api.siliconflow.cn/v1/embeddings"
      model: "BAAI/bge-large-zh-v1.5"
      rate_limit: 50
    - api_key: "sk-yyy"
      api_base: "https://api.siliconflow.cn/v1/embeddings"
      model: "BAAI/bge-large-zh-v1.5"
      rate_limit: 50 